#ifndef DEFINE
#define DEFINE

#define WITH_DEFAULT 0
#define WITH_SHIFT 1
#define WITH_CTRL 2
#define WITH_ALT 3
#define WITH_CTRL_SHIFT 4
#define WITH_ALT_SHIFT 5
#define WITH_ALT_CTRL 6
#define WITH_ALT_CTRL_SHIFT 7
#define WITH_TAB 8
#define WITH_CAPS 9

#define GUI_KEYBOARD_NULL 0

#define GUI_OFF 0
#define GUI_ON 1

#define GUI_SPACE_CLICKED 16
#define GUI_SPACE_PRESSED 17

#define GUI_COMMA_CLICKED 18
#define GUI_COMMA_PRESSED 19

#define GUI_MINUS_PRESSED 20
#define GUI_MINUS_CLICKED 21

#define GUI_PERIOD_CLICKED 22
#define GUI_PERIOD_PRESSED 23

#define GUI_SLASH_CLICKED 24
#define GUI_SLASH_PRESSED 25

#define GUI_0_CLICKED 26
#define GUI_0_PRESSED 27

#define GUI_1_CLICKED 28
#define GUI_1_PRESSED 29

#define GUI_2_CLICKED 30
#define GUI_2_PRESSED 31

#define GUI_3_CLICKED 32
#define GUI_3_PRESSED 33

#define GUI_4_CLICKED 34
#define GUI_4_PRESSED 35

#define GUI_5_CLICKED 36
#define GUI_5_PRESSED 37

#define GUI_6_CLICKED 38
#define GUI_6_PRESSED 39

#define GUI_7_CLICKED 40
#define GUI_7_PRESSED 41

#define GUI_8_CLICKED 42
#define GUI_8_PRESSED 43

#define GUI_9_CLICKED 44
#define GUI_9_PRESSED 45

#define GUI_SEMICOLON_CLICKED 46
#define GUI_SEMICOLON_PRESSED 47

#define GUI_EQUAL_CLICKED 48
#define GUI_EQUAL_PRESSED 49

#define GUI_A_CLICKED 50
#define GUI_A_PRESSED 51

#define GUI_B_CLICKED 52
#define GUI_B_PRESSED 53

#define GUI_C_CLICKED 54
#define GUI_C_PRESSED 55

#define GUI_D_CLICKED 56
#define GUI_D_PRESSED 57

#define GUI_E_CLICKED 58
#define GUI_E_PRESSED 59

#define GUI_F_CLICKED 60
#define GUI_F_PRESSED 61

#define GUI_G_CLICKED 62
#define GUI_G_PRESSED 63

#define GUI_H_CLICKED 64
#define GUI_H_PRESSED 65

#define GUI_I_CLICKED 66
#define GUI_I_PRESSED 67

#define GUI_J_CLICKED 68
#define GUI_J_PRESSED 69

#define GUI_K_CLICKED 70
#define GUI_K_PRESSED 71

#define GUI_L_CLICKED 72
#define GUI_L_PRESSED 73

#define GUI_M_CLICKED 74
#define GUI_M_PRESSED 75

#define GUI_N_CLICKED 76
#define GUI_N_PRESSED 77

#define GUI_O_CLICKED 78
#define GUI_O_PRESSED 79

#define GUI_P_CLICKED 80
#define GUI_P_PRESSED 81

#define GUI_Q_CLICKED 82
#define GUI_Q_PRESSED 83

#define GUI_R_CLICKED 84
#define GUI_R_PRESSED 85

#define GUI_S_CLICKED 86
#define GUI_S_PRESSED 87

#define GUI_T_CLICKED 88
#define GUI_T_PRESSED 89

#define GUI_U_CLICKED 90
#define GUI_U_PRESSED 91

#define GUI_V_CLICKED 92
#define GUI_V_PRESSED 93

#define GUI_W_CLICKED 94
#define GUI_W_PRESSED 95

#define GUI_X_CLICKED 96
#define GUI_X_PRESSED 97

#define GUI_Y_CLICKED 98
#define GUI_Y_PRESSED 99

#define GUI_Z_CLICKED 100
#define GUI_Z_PRESSED 101

#define GUI_LEFTBRACKET_CLICKED 102
#define GUI_LEFTBRACKET_PRESSED 103

#define GUI_BACKSLASH_CLICKED 104
#define GUI_BACKSLASH_PRESSED 105

#define GUI_RIGHTBRACKET_CLICKED 106
#define GUI_RIGHTBRACKET_PRESSED 107

#define GUI_ESCAPE_CLICKED 108
#define GUI_ESCAPE_PRESSED 109 

#define GUI_ENTER_CLICKED 110
#define GUI_ENTER_PRESSED 111

#define GUI_TAB_CLICKED 112
#define GUI_TAB_PRESSED 113

#define GUI_BACKSPACE_CLICKED 114
#define GUI_BACKSPACE_PRESSED 115

#define GUI_INSERT_CLICKED 116
#define GUI_INSERT_PRESSED 117

#define GUI_DELETE_CLICKED 118
#define GUI_DELETE_PRESSED 119

#define GUI_RIGHT_CLICKED 120
#define GUI_RIGHT_PRESSED 121

#define GUI_LEFT_CLICKED 122
#define GUI_LEFT_PRESSED 123

#define GUI_DOWN_CLICKED 124
#define GUI_DOWN_PRESSED 125

#define GUI_UP_CLICKED 126
#define GUI_UP_PRESSED 127

#define GUI_PAGEUP_CLICKED 128
#define GUI_PAGEUP_PRESSED 129

#define GUI_PAGEDOWN_CLICKED 130
#define GUI_PAGEDOWN_PRESSED 131
			
#define GUI_HOME_CLICKED 132
#define GUI_HOME_PRESSED 133

#define GUI_END_CLICKED 134
#define GUI_END_PRESSED 135

////////////////caps lock skipped

#define GUI_SCROLLLOCK_CLICKED 136
#define GUI_SCROLLLOCK_PRESSED 137

#define GUI_NUMLOCK_CLICKED 138
#define GUI_NUMLOCK_PRESSED 139

#define GUI_PRINTSCREEN_CLICKED 140
#define GUI_PRINTSCREEN_PRESSED 141

#define GUI_PAUSE_CLICKED 142
#define GUI_PAUSE_PRESSED 143

#define GUI_F1_CLICKED 144
#define GUI_F1_PRESSED 145

#define GUI_F2_CLICKED 146
#define GUI_F2_PRESSED 147

#define GUI_F3_CLICKED 148
#define GUI_F3_PRESSED 149

#define GUI_F4_CLICKED 150
#define GUI_F4_PRESSED 151

#define GUI_F5_CLICKED 152
#define GUI_F5_PRESSED 153

#define GUI_F6_CLICKED 154
#define GUI_F6_PRESSED 155

#define GUI_F7_CLICKED 156
#define GUI_F7_PRESSED 157

#define GUI_F8_CLICKED 158
#define GUI_F8_PRESSED 159

#define GUI_F9_CLICKED 160
#define GUI_F9_PRESSED 161

#define GUI_F10_CLICKED 162
#define GUI_F10_PRESSED 163
						
#define GUI_F11_CLICKED 164
#define GUI_F11_PRESSED 165
						
#define GUI_F12_CLICKED 166
#define GUI_F12_PRESSED 167
						
#define GUI_F13_CLICKED 168
#define GUI_F13_PRESSED 169
						
#define GUI_F14_CLICKED 170
#define GUI_F14_PRESSED 171
						
#define GUI_F15_CLICKED 172
#define GUI_F15_PRESSED 173
						
#define GUI_F16_CLICKED 174
#define GUI_F16_PRESSED 175
						
#define GUI_F17_CLICKED 176
#define GUI_F17_PRESSED 177
						
#define GUI_F18_CLICKED 178
#define GUI_F18_PRESSED 179
						
#define GUI_F19_CLICKED 180
#define GUI_F19_PRESSED 181
						
#define GUI_F20_CLICKED 182
#define GUI_F20_PRESSED 183
						
#define GUI_F21_CLICKED 184
#define GUI_F21_PRESSED 185
						
#define GUI_F22_CLICKED 186
#define GUI_F22_PRESSED 187
						
#define GUI_F23_CLICKED 188
#define GUI_F23_PRESSED 189
						
#define GUI_F24_CLICKED 190
#define GUI_F24_PRESSED 191
						
#define GUI_F25_CLICKED 192
#define GUI_F25_PRESSED 193
						
#define GUI_KP0_CLICKED 194
#define GUI_KP0_PRESSED 195
						
#define GUI_KP1_CLICKED 196
#define GUI_KP1_PRESSED 197
						
#define GUI_KP2_CLICKED 198
#define GUI_KP2_PRESSED 199
						
#define GUI_KP3_CLICKED 200
#define GUI_KP3_PRESSED 201
						
#define GUI_KP4_CLICKED 202
#define GUI_KP4_PRESSED 203
						
#define GUI_KP5_CLICKED 204
#define GUI_KP5_PRESSED 205
					
#define GUI_KP6_CLICKED 206
#define GUI_KP6_PRESSED 207
						
#define GUI_KP7_CLICKED 208
#define GUI_KP7_PRESSED 209

#define GUI_KP8_CLICKED 210
#define GUI_KP8_PRESSED 211
						
#define GUI_KP9_CLICKED 212
#define GUI_KP9_PRESSED 213

#define GUI_KP_DECIMAL_CLICKED 214
#define GUI_KP_DECIMAL_PRESSED 215

#define GUI_KP_DEVIDE__CLICKED 216
#define GUI_KP_DEVIDE__PRESSED 217

#define GUI_KP_MULTIPLY_CLICKED 218
#define GUI_KP_MULTIPLY_PRESSED 219

#define GUI_KP_SUBTRACT_CLICKED 220
#define GUI_KP_SUBTRACT_PRESSED 221

#define GUI_KP_ADD_CLICKED 222
#define GUI_KP_ADD_PRESSED 223

#define GUI_KP_ENTER_CLICKED 224
#define GUI_KP_ENTER_PRESSED 225

#define GUI_KP_EQUAL_CLICKED 226
#define GUI_KP_EQUAL_PRESSED 227













#endif